language: go

os:
  - linux
  
go: 
  - "1.12.x"
  - tip

env:
  - GO111MODULE=on

install:
  - go get -u golang.org/x/lint/golint
  - go get -u golang.org/x/tools/cmd/goimports
  - go get -u golang.org/x/text/cmd/gotext
  
script:
 - go generate ./...
 - go test -race -v -coverprofile=coverage.txt -covermode=atomic ./...
 - go vet ./...
 - diff <(golint ./...) <(printf "")

after_success:
  - bash <(curl -s https://codecov.io/bash)
  
