version: "{build}"

os: Windows Server 2012 R2

clone_folder: c:\github.com\bvwells\go-i18n

install:
  - echo %PATH%
  - echo %GOPATH%
  - go version
  - go env
  - go get -u golang.org/x/text/cmd/gotext

build_script:
 - go generate ./...
 - go install -v ./...

test_script:
 - go test -race -v ./...
