// Code generated by running "go generate" in golang.org/x/text. DO NOT EDIT.

package main

import (
	"golang.org/x/text/language"
	"golang.org/x/text/message"
	"golang.org/x/text/message/catalog"
)

type dictionary struct {
	index []uint32
	data  string
}

func (d *dictionary) Lookup(key string) (data string, ok bool) {
	p := messageKeyToIndex[key]
	start, end := d.index[p], d.index[p+1]
	if start == end {
		return "", false
	}
	return d.data[start:end], true
}

func init() {
	dict := map[string]catalog.Dictionary{
		"en": &dictionary{index: enIndex, data: enData},
		"es": &dictionary{index: esIndex, data: esData},
	}
	fallback := language.MustParse("en")
	cat, err := catalog.NewFromMap(dict, catalog.Fallback(fallback))
	if err != nil {
		panic(err)
	}
	message.DefaultCatalog = cat
}

var messageKeyToIndex = map[string]int{
	"Hello world!": 0,
}

var enIndex = []uint32{ // 2 elements
	0x00000000, 0x0000000d,
} // Size: 32 bytes

const enData string = "\x02Hello world!"

var esIndex = []uint32{ // 2 elements
	0x00000000, 0x0000000e,
} // Size: 32 bytes

const esData string = "\x02¡Hola Mundo!"

// Total table size 91 bytes (0KiB); checksum: 4F7AE4FA
